whereiam = "<#16de87>You are currently on the proxy <#16de8><proxy> <#16de87>(<#16de8><server><#16de87>)"
whereis = "<#16de87><#16de8><player><#16de87> is currently on the proxy <#16de8><proxy><#16de87> (<#16de8><server><#16de87>)"
sending-player = "<#16de87>Sending <#16de8><player><#16de87> to <#16de8><server><#16de87>..."
player-already-on-server = "<#16de87><#16de8><player><#16de87> is already on <#16de8><server><#16de87>!"
player-sent-success = "<#16de87><#16de8><player><#16de87> has been sent to <#16de8><server><#16de87>!"
player-sent-fail = "<#16de87>Failed to send <#16de8><player><#16de87> to <#16de8><server><#16de87>!"
send-all-players = "<#16de87>Sending <players> players to <#16de8><server><#16de87>..."
send-all-players-success = "<#16de87>All players have been sent to <#16de8><server><#16de87>!"
send-all-players-fail = "<#16de87>Failed to send all players to <#16de8><server><#16de87>!"
send-all-players-from-server = "<#16de87>Sending <players> players from <#16de8><source><#16de87> to <#16de8><target><#16de87>..."
send-all-players-from-server-fail = "<#16de87>Failed to send all players from <#16de8><source><#16de87> to <#16de8><target><#16de87>!"
send-all-players-from-server-success = "<#16de87>All players from <#16de8><source><#16de87> have been sent to <#16de8><target><#16de87>!"
group-not-found = "<#16de87>Group <#16de8><group><#16de87> not found!"
clean-restart-started = "<#16de87>Restarting <#16de8><source><#16de87>... Players will be sent to <#16de8><target><#16de87>!"
group-empty = "<#16de87>Cannot start clean restart, group <#16de8><group><#16de87> is empty!"
server-rebooted = "<#16de87><#16de8><server><#16de87> has been rebooted! (<#16de8><rebooted><#16de87>/<#16de8><total><#16de87>)"
clean-restart-done = "<#16de87>All <#16de8><group><#16de87> servers have been restarted!"
group-already-restarting = "<#16de87>Group <#16de8><group><#16de87> is already restarting!"